[theme]
# Primary accent colour for interactive elements.
primaryColor = "#ffffff"

# Background colour for the main content area.
backgroundColor = "#ffffff"

# Background colour used for the sidebar and widgets
secondaryBackgroundColor = "#d5e3ac"

# Color used for almost all text.
textColor = "#000000"


[client]
toolbarMode = "minimal"
